import { useState, type FormEvent } from 'react'
import { z } from 'zod'
import { Banner } from '../../components/ui/Banner'
import { Button } from '../../components/ui/Button'
import { FormError } from '../../components/ui/FormError'
import { Input } from '../../components/ui/Input'
import { Label } from '../../components/ui/Label'
import { LoadingScreen } from '../../components/ui/LoadingScreen'
import { toFriendlyDbErrorMessage } from '../../lib/errorMessages'
import type { Child, FamilyMemberRole } from '../../types/database'
import { useAuth } from '../auth/useAuth'
import { useOnboardingStatus } from '../onboarding/useOnboardingStatus'
import { INVITE_VALIDITY_DAYS } from './api'
import { SettingsHeader } from './SettingsHeader'
import {
  useCreateFamilyInvite,
  useFamilyMembers,
  useUpdateBabyDetails,
} from './useBabyFamily'

/**
 * "Baby & family" settings sub-screen (spec section 3.2). Three shared,
 * per-family/per-child concerns on one screen:
 *   - the baby's name + birth date (per-child, editable -> `children`)
 *   - the family members list (per-family, read from the
 *     `family_members_with_identity` RPC so the other parent's real name/email
 *     is shown, not just an id)
 *   - inviting a second parent (per-family, reusing the existing onboarding
 *     invite mechanism: a `family_invites` row whose token is generated by the
 *     DB and consumed by the existing `/join?token=` screen)
 *
 * All Supabase access is in the settings `api.ts` + `useBabyFamily` hooks.
 */

// --- child name + birth date ---------------------------------------------

const todayIsoDate = new Date().toISOString().slice(0, 10)

const babyDetailsSchema = z.object({
  name: z.string().trim().min(1, 'צריך להזין שם'),
  birthDate: z
    .string()
    .min(1, 'צריך להזין תאריך לידה')
    .refine((value) => value <= todayIsoDate, 'תאריך הלידה לא יכול להיות בעתיד'),
})

interface BabyDetailsFieldErrors {
  name?: string
  birthDate?: string
}

// --- family members -------------------------------------------------------

const ROLE_LABELS: Record<FamilyMemberRole, string> = {
  parent: 'הורה',
}

// --- invite second parent -------------------------------------------------

function inviteLinkFor(token: string): string {
  return `${window.location.origin}/join?token=${encodeURIComponent(token)}`
}

// --- screen ---------------------------------------------------------------

export function BabyFamilyScreen() {
  const { data: onboardingState, isLoading } = useOnboardingStatus()

  if (isLoading) return <LoadingScreen />

  return (
    <div className="min-h-screen bg-neutral-50 px-5 pb-16 pt-6">
      <div className="mx-auto w-full max-w-sm">
        <SettingsHeader title="תינוק ומשפחה" backTo="/settings" />

        {onboardingState?.familyId && onboardingState.firstChild ? (
          <BabyFamilyContent
            familyId={onboardingState.familyId}
            child={onboardingState.firstChild}
          />
        ) : (
          <div className="mt-6">
            <Banner variant="error" message="לא הצלחנו לטעון את פרטי המשפחה. נסה שוב." />
          </div>
        )}
      </div>
    </div>
  )
}

interface BabyFamilyContentProps {
  familyId: string
  child: Child
}

/**
 * The loaded content. Split out so the baby-details form can initialise its
 * local state from the already-fetched child (mounts only once data is ready).
 */
function BabyFamilyContent({ familyId, child }: BabyFamilyContentProps) {
  const { user } = useAuth()

  const [name, setName] = useState(child.name)
  const [birthDate, setBirthDate] = useState(child.birth_date)
  const [fieldErrors, setFieldErrors] = useState<BabyDetailsFieldErrors>({})
  const [savedJustNow, setSavedJustNow] = useState(false)
  const [copied, setCopied] = useState(false)

  const membersQuery = useFamilyMembers(familyId)

  const updateMutation = useUpdateBabyDetails(child.id)
  const inviteMutation = useCreateFamilyInvite(familyId, user!.id)

  function handleSaveDetails(event: FormEvent) {
    event.preventDefault()
    setSavedJustNow(false)
    const result = babyDetailsSchema.safeParse({ name, birthDate })
    if (!result.success) {
      const errors: BabyDetailsFieldErrors = {}
      for (const issue of result.error.issues) {
        const field = issue.path[0] as keyof BabyDetailsFieldErrors
        errors[field] = issue.message
      }
      setFieldErrors(errors)
      return
    }
    setFieldErrors({})
    updateMutation.mutate(result.data, {
      onSuccess: () => setSavedJustNow(true),
    })
  }

  async function handleCopyInvite(link: string) {
    try {
      await navigator.clipboard.writeText(link)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard can be unavailable (permissions / insecure context); the link
      // stays visible on screen for the parent to copy manually, so no error
      // surface is needed here.
    }
  }

  const inviteLink = inviteMutation.data ? inviteLinkFor(inviteMutation.data.token) : null

  return (
    <div className="mt-6 flex flex-col gap-6">
      {/* Baby name + birth date (per-child) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-4 text-sm font-semibold text-neutral-900">פרטי התינוק/ת</h2>

        <form onSubmit={handleSaveDetails} noValidate className="flex flex-col gap-4">
          <div>
            <Label htmlFor="babyName">שם</Label>
            <Input
              id="babyName"
              value={name}
              hasError={Boolean(fieldErrors.name)}
              onChange={(event) => {
                setName(event.target.value)
                setSavedJustNow(false)
              }}
            />
            <FormError message={fieldErrors.name} />
          </div>

          <div>
            <Label htmlFor="babyBirthDate">תאריך לידה</Label>
            <Input
              id="babyBirthDate"
              type="date"
              value={birthDate}
              hasError={Boolean(fieldErrors.birthDate)}
              onChange={(event) => {
                setBirthDate(event.target.value)
                setSavedJustNow(false)
              }}
            />
            <FormError message={fieldErrors.birthDate} />
          </div>

          {updateMutation.isError && (
            <Banner variant="error" message={toFriendlyDbErrorMessage(updateMutation.error)} />
          )}
          {savedJustNow && !updateMutation.isError && (
            <Banner variant="info" message="הפרטים נשמרו." />
          )}

          <Button type="submit" isLoading={updateMutation.isPending}>
            שמירה
          </Button>
        </form>
      </section>

      {/* Family members (per-family, read-only) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-4 text-sm font-semibold text-neutral-900">חברי המשפחה</h2>

        {membersQuery.isLoading && <p className="text-sm text-neutral-600">טוען...</p>}

        {membersQuery.isError && (
          <Banner variant="error" message={toFriendlyDbErrorMessage(membersQuery.error)} />
        )}

        {membersQuery.data && (
          <ul className="flex flex-col gap-2">
            {membersQuery.data.map((member) => {
              const isCurrentUser = member.user_id === user?.id
              // Prefer the member's chosen display name, then their email; fall
              // back to the role only if neither is set (both come from the
              // identity RPC, which exposes them for every family member).
              const primaryLabel =
                member.display_name ?? member.email ?? ROLE_LABELS[member.role]
              return (
                <li
                  key={member.id}
                  className="flex items-center justify-between gap-3 rounded-md bg-neutral-50 px-3 py-2.5"
                >
                  <span className="min-w-0">
                    <span className="block truncate text-sm text-neutral-900" dir="auto">
                      {primaryLabel}
                      {isCurrentUser && (
                        <span className="ms-2 text-xs text-neutral-500">(אתה)</span>
                      )}
                    </span>
                    {member.display_name && member.email && (
                      <span className="block truncate text-xs text-neutral-500" dir="ltr">
                        {member.email}
                      </span>
                    )}
                  </span>
                  <span className="shrink-0 text-xs font-medium text-neutral-500">
                    {ROLE_LABELS[member.role]}
                  </span>
                </li>
              )
            })}
          </ul>
        )}
      </section>

      {/* Invite second parent (per-family, reuses the onboarding invite flow) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-1 text-sm font-semibold text-neutral-900">הזמנת הורה נוסף</h2>
        <p className="mb-4 text-sm text-neutral-600">
          צרו קישור הזמנה ושלחו אותו להורה השני כדי שיצטרף לאותה משפחה.
        </p>

        {inviteMutation.isError && (
          <div className="mb-4">
            <Banner variant="error" message={toFriendlyDbErrorMessage(inviteMutation.error)} />
          </div>
        )}

        {inviteLink ? (
          <div className="flex flex-col gap-3">
            <div className="break-all rounded-md bg-neutral-50 px-3 py-2.5 text-sm text-neutral-800">
              {inviteLink}
            </div>
            <p className="text-xs text-neutral-500">
              הקישור תקף ל־{INVITE_VALIDITY_DAYS} ימים ולשימוש חד־פעמי.
            </p>
            <Button
              type="button"
              variant="secondary"
              onClick={() => void handleCopyInvite(inviteLink)}
            >
              {copied ? 'הקישור הועתק' : 'העתקת הקישור'}
            </Button>
          </div>
        ) : (
          <Button
            type="button"
            isLoading={inviteMutation.isPending}
            onClick={() => inviteMutation.mutate()}
          >
            יצירת קישור הזמנה
          </Button>
        )}
      </section>
    </div>
  )
}
