import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { z } from 'zod'
import { Banner } from '../../components/ui/Banner'
import { Button } from '../../components/ui/Button'
import { FormError } from '../../components/ui/FormError'
import { Input } from '../../components/ui/Input'
import { Label } from '../../components/ui/Label'
import { LoadingScreen } from '../../components/ui/LoadingScreen'
import { supabase } from '../../lib/supabase'
import { toFriendlyDbErrorMessage } from '../../lib/errorMessages'
import type { Child, FamilyInvite, FamilyMember } from '../../types/database'
import { useAuth } from '../auth/useAuth'
import { useOnboardingStatus } from '../onboarding/useOnboardingStatus'
import { SettingsHeader } from './SettingsHeader'

/**
 * "Baby & family" settings sub-screen (spec section 3.2). Three shared,
 * per-family/per-child concerns on one screen:
 *   - the baby's name + birth date (per-child, editable -> `children`)
 *   - the family members list (per-family, read-only from `family_members`)
 *   - inviting a second parent (per-family, reusing the existing onboarding
 *     invite mechanism: a `family_invites` row whose token is generated by the
 *     DB and consumed by the existing `/join?token=` screen)
 *
 * NOTE: normally the Supabase calls + query hooks below would live in a feature
 * `api.ts` / `use*.ts`. This slice is intentionally scoped to a single file, so
 * they are colocated here rather than spread across new files.
 */

// --- child name + birth date ---------------------------------------------

const todayIsoDate = new Date().toISOString().slice(0, 10)

const babyDetailsSchema = z.object({
  name: z.string().trim().min(1, 'צריך להזין שם'),
  birthDate: z
    .string()
    .min(1, 'צריך להזין תאריך לידה')
    .refine((value) => value <= todayIsoDate, 'תאריך הלידה לא יכול להיות בעתיד'),
})

type BabyDetailsInput = z.infer<typeof babyDetailsSchema>

interface BabyDetailsFieldErrors {
  name?: string
  birthDate?: string
}

async function updateBabyDetails(childId: string, input: BabyDetailsInput): Promise<Child> {
  const { data, error } = await supabase
    .from('children')
    .update({ name: input.name, birth_date: input.birthDate })
    .eq('id', childId)
    .select()
    .single<Child>()

  if (error) throw error
  return data
}

// --- family members -------------------------------------------------------

type FamilyMemberRow = Pick<FamilyMember, 'id' | 'user_id' | 'role'>

const ROLE_LABELS: Record<FamilyMember['role'], string> = {
  parent: 'הורה',
}

async function fetchFamilyMembers(familyId: string): Promise<FamilyMemberRow[]> {
  const { data, error } = await supabase
    .from('family_members')
    .select('id, user_id, role')
    .eq('family_id', familyId)
    .returns<FamilyMemberRow[]>()

  if (error) throw error
  return data
}

// --- invite second parent -------------------------------------------------

/** Days an invite link stays valid. Matches the onboarding invite lifetime. */
const INVITE_VALIDITY_DAYS = 7

async function createFamilyInvite(familyId: string, invitedBy: string): Promise<FamilyInvite> {
  const expiresAt = new Date(
    Date.now() + INVITE_VALIDITY_DAYS * 24 * 60 * 60 * 1000,
  ).toISOString()

  // Reuse the existing invite mechanism: the token column defaults to
  // gen_random_uuid() in the DB, and the resulting link is consumed by the
  // existing JoinFamilyScreen (`/join?token=`). No token logic is duplicated.
  const { data, error } = await supabase
    .from('family_invites')
    .insert({ family_id: familyId, invited_by: invitedBy, expires_at: expiresAt })
    .select()
    .single<FamilyInvite>()

  if (error) throw error
  return data
}

function inviteLinkFor(token: string): string {
  return `${window.location.origin}/join?token=${encodeURIComponent(token)}`
}

// --- screen ---------------------------------------------------------------

export function BabyFamilyScreen() {
  const { data: onboardingState, isLoading } = useOnboardingStatus()

  if (isLoading) return <LoadingScreen />

  return (
    <div className="min-h-screen bg-neutral-50 px-5 pb-16 pt-6">
      <div className="mx-auto w-full max-w-sm">
        <SettingsHeader title="תינוק ומשפחה" backTo="/settings" />

        {onboardingState?.familyId && onboardingState.firstChild ? (
          <BabyFamilyContent
            familyId={onboardingState.familyId}
            child={onboardingState.firstChild}
          />
        ) : (
          <div className="mt-6">
            <Banner variant="error" message="לא הצלחנו לטעון את פרטי המשפחה. נסה שוב." />
          </div>
        )}
      </div>
    </div>
  )
}

interface BabyFamilyContentProps {
  familyId: string
  child: Child
}

/**
 * The loaded content. Split out so the baby-details form can initialise its
 * local state from the already-fetched child (mounts only once data is ready).
 */
function BabyFamilyContent({ familyId, child }: BabyFamilyContentProps) {
  const { user } = useAuth()
  const queryClient = useQueryClient()

  const [name, setName] = useState(child.name)
  const [birthDate, setBirthDate] = useState(child.birth_date)
  const [fieldErrors, setFieldErrors] = useState<BabyDetailsFieldErrors>({})
  const [savedJustNow, setSavedJustNow] = useState(false)
  const [copied, setCopied] = useState(false)

  const membersQuery = useQuery({
    queryKey: ['family-members', familyId],
    queryFn: () => fetchFamilyMembers(familyId),
  })

  const updateMutation = useMutation({
    mutationFn: (input: BabyDetailsInput) => updateBabyDetails(child.id, input),
    onSuccess: async () => {
      setSavedJustNow(true)
      await queryClient.invalidateQueries({ queryKey: ['onboarding-status', user?.id] })
    },
  })

  const inviteMutation = useMutation({
    mutationFn: () => createFamilyInvite(familyId, user!.id),
  })

  function handleSaveDetails(event: FormEvent) {
    event.preventDefault()
    setSavedJustNow(false)
    const result = babyDetailsSchema.safeParse({ name, birthDate })
    if (!result.success) {
      const errors: BabyDetailsFieldErrors = {}
      for (const issue of result.error.issues) {
        const field = issue.path[0] as keyof BabyDetailsFieldErrors
        errors[field] = issue.message
      }
      setFieldErrors(errors)
      return
    }
    setFieldErrors({})
    updateMutation.mutate(result.data)
  }

  async function handleCopyInvite(link: string) {
    try {
      await navigator.clipboard.writeText(link)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard can be unavailable (permissions / insecure context); the link
      // stays visible on screen for the parent to copy manually, so no error
      // surface is needed here.
    }
  }

  const inviteLink = inviteMutation.data ? inviteLinkFor(inviteMutation.data.token) : null

  return (
    <div className="mt-6 flex flex-col gap-6">
      {/* Baby name + birth date (per-child) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-4 text-sm font-semibold text-neutral-900">פרטי התינוק/ת</h2>

        <form onSubmit={handleSaveDetails} noValidate className="flex flex-col gap-4">
          <div>
            <Label htmlFor="babyName">שם</Label>
            <Input
              id="babyName"
              value={name}
              hasError={Boolean(fieldErrors.name)}
              onChange={(event) => {
                setName(event.target.value)
                setSavedJustNow(false)
              }}
            />
            <FormError message={fieldErrors.name} />
          </div>

          <div>
            <Label htmlFor="babyBirthDate">תאריך לידה</Label>
            <Input
              id="babyBirthDate"
              type="date"
              value={birthDate}
              hasError={Boolean(fieldErrors.birthDate)}
              onChange={(event) => {
                setBirthDate(event.target.value)
                setSavedJustNow(false)
              }}
            />
            <FormError message={fieldErrors.birthDate} />
          </div>

          {updateMutation.isError && (
            <Banner variant="error" message={toFriendlyDbErrorMessage(updateMutation.error)} />
          )}
          {savedJustNow && !updateMutation.isError && (
            <Banner variant="info" message="הפרטים נשמרו." />
          )}

          <Button type="submit" isLoading={updateMutation.isPending}>
            שמירה
          </Button>
        </form>
      </section>

      {/* Family members (per-family, read-only) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-4 text-sm font-semibold text-neutral-900">חברי המשפחה</h2>

        {membersQuery.isLoading && <p className="text-sm text-neutral-600">טוען...</p>}

        {membersQuery.isError && (
          <Banner variant="error" message={toFriendlyDbErrorMessage(membersQuery.error)} />
        )}

        {membersQuery.data && (
          <ul className="flex flex-col gap-2">
            {membersQuery.data.map((member) => {
              const isCurrentUser = member.user_id === user?.id
              return (
                <li
                  key={member.id}
                  className="flex items-center justify-between gap-3 rounded-md bg-neutral-50 px-3 py-2.5"
                >
                  <span className="text-sm text-neutral-900">
                    {isCurrentUser ? user?.email ?? 'אתה' : ROLE_LABELS[member.role]}
                    {isCurrentUser && (
                      <span className="ms-2 text-xs text-neutral-500">(אתה)</span>
                    )}
                  </span>
                  <span className="text-xs font-medium text-neutral-500">
                    {ROLE_LABELS[member.role]}
                  </span>
                </li>
              )
            })}
          </ul>
        )}
      </section>

      {/* Invite second parent (per-family, reuses the onboarding invite flow) */}
      <section className="rounded-lg border border-neutral-200 bg-neutral-0 p-4 shadow-sm">
        <h2 className="mb-1 text-sm font-semibold text-neutral-900">הזמנת הורה נוסף</h2>
        <p className="mb-4 text-sm text-neutral-600">
          צרו קישור הזמנה ושלחו אותו להורה השני כדי שיצטרף לאותה משפחה.
        </p>

        {inviteMutation.isError && (
          <div className="mb-4">
            <Banner variant="error" message={toFriendlyDbErrorMessage(inviteMutation.error)} />
          </div>
        )}

        {inviteLink ? (
          <div className="flex flex-col gap-3">
            <div className="break-all rounded-md bg-neutral-50 px-3 py-2.5 text-sm text-neutral-800">
              {inviteLink}
            </div>
            <p className="text-xs text-neutral-500">
              הקישור תקף ל־{INVITE_VALIDITY_DAYS} ימים ולשימוש חד־פעמי.
            </p>
            <Button
              type="button"
              variant="secondary"
              onClick={() => void handleCopyInvite(inviteLink)}
            >
              {copied ? 'הקישור הועתק' : 'העתקת הקישור'}
            </Button>
          </div>
        ) : (
          <Button
            type="button"
            isLoading={inviteMutation.isPending}
            onClick={() => inviteMutation.mutate()}
          >
            יצירת קישור הזמנה
          </Button>
        )}
      </section>
    </div>
  )
}
